---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: Coloumns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library("tidyverse")
```



```{r include=FALSE}
df <- read.csv("customer-churn.csv")
df
```

```{r}
library(plotly)
```


```{r}
library(readr)
```

```{r include=FALSE}
glimpse(df)
```

Column
-----------------------------------------------------------------------
### ABC
```{r}
# Box Plot
ggplot(data = df, aes(x = Churn, y = tenure, fill = Churn)) +
  geom_boxplot()
```

Column
-----------------------------------------------------------------------
### Chrat B
```{r}
# Bar Chart
ggplot(data = df, aes(x = InternetService, fill = MonthlyCharges)) +
  geom_bar() +
  theme_classic() +
  labs(
    title = "Perbandingan Amount Charge Montly by Tipe Service",
    caption = "Sumber Data: Marketing"
  ) +
  xlab("InternetService") +
  ylab("MonthlyCharges") +
  theme(legend.position = "none")
```


Column
-----------------------------------------------------------------------
### CD
```{r}
ggplot(data = df, aes(x = Contract, fill = Contract)) +
  geom_bar()
```
